### ISSUE TITLE
Additional empty directory created by pvtk_grid

### ISSUE THREAD

**Issue by kaipartmann** [JuliaVTK/WriteVTK.jl#142]
First, thanks for the fast updates regarding #139!
I already updated to `v1.19` and it works like a charm!

However, when exporting with pvtk_grid, an additional empty directory `<filename>_dir` is created.
This can be reproduced with the example provided here: https://github.com/JuliaVTK/WriteVTK.jl/issues/139#issuecomment-2036483267

**Comment by jipolanco** [comment]
Oops, thanks for catching that!

That was meant as a test and shouldn't have been committed :)
