### ISSUE TITLE
Parallel writing to ParaView collections

### ISSUE THREAD

**Issue by ZenanH** [JuliaVTK/WriteVTK.jl#150]
Hi,

Currently, I can read data from `.jld2` files and write to ParaView collections. However, the process is sometimes slow, so I want to use multithreading. At the moment, I do it like this:

```julia
paraview_collection(mps_path) do pvd
    @inbounds Threads.@threads for i in 1:itr
        jldopen(jld2dir, "r"; parallel_read=true) do fid
            # read data from jld2 file
            time = fid["group$(i)/time"]
            sig  = fid["group$(i)/sig" ]
            ...

            # write data
            VTU_cls = [MeshCell(VTKCellTypes.VTK_VERTEX, [j]) for j in 1:mp_num]
            VTU_pts = Array{Float64}(mp_pos')
            let vtk = vtk_grid(joinpath(anim_path, "iter_$(i)"), VTU_pts, VTU_cls)
                vtk["stress"] = sig[:, [1, 2, 4]]'
                ...

                pvd[time] = vtk
            end
        end
    end
end
```

But I still encounter occasional shaking in the video (https://github.com/JuliaIO/JLD2.jl/pull/477#issuecomment-2373534576). I wonder if this issue is due to ParaView collections not supporting multithreaded mode?

**Comment by jipolanco** [comment]
Yes, this is not very surprising to me. At this moment we do nothing to ensure that one can safely write to a ParaView collection in parallel. You can take a look at the implementation [here](https://github.com/JuliaVTK/WriteVTK.jl/blob/74e55ff0079cfdc971292f0e0cea301573bdcba1/src/gridtypes/ParaviewCollection.jl#L62).

I see two possible issues:

1. I don't know how LightXML.jl (or libxml2) handles writing to a same XML document in parallel. If that's not explicitly supported by these libraries, you could get some corrupted XML file or some XML elements missing (=> missing timesteps in the ParaView collection). Your outputs seem to open correctly in ParaView so I guess your files are at least "proper" XML.

2. Even if all timesteps are correctly written to the ParaView collection, they will generally not be in the right order. For example, thread 2 may write its timestep before thread 1 if it arrives first to the `pvd[time] = vtk` line. From your video in the linked issue, it seems like ParaView doesn't reorder the timesteps, and therefore you see random jumps forward and backward in time.

So you need to make sure that timesteps are written sequentially to the ParaView collection, even if the actual datasets are written in parallel. The first issue would be easily fixed using [locks](https://docs.julialang.org/en/v1/base/parallel/#Base.ReentrantLock), but that doesn't completely fix the same issue, which would require some careful ordering of the threads.

Perhaps the easiest solution is to store in a vector the VTK files and times during the parallel loop, and to write them later to a PVD file in a serial loop. I haven't tried it, but something like this should work:

```julia
vtk_files = Vector{WriteVTK.DatasetFile}(undef, itr)
times = Vector{Float64}(undef, itr)

@inbounds Threads.@threads for i in 1:itr
    jldopen(jld2dir, "r"; parallel_read=true) do fid
        # read data from jld2 file
        time = fid["group$(i)/time"]
        sig  = fid["group$(i)/sig" ]
        ...

        # write data
        VTU_cls = [MeshCell(VTKCellTypes.VTK_VERTEX, [j]) for j in 1:mp_num]
        VTU_pts = Array{Float64}(mp_pos')
        let vtk = vtk_grid(joinpath(anim_path, "iter_$(i)"), VTU_pts, VTU_cls)
            vtk["stress"] = sig[:, [1, 2, 4]]'
            ...
            times[i] = time
            vtk_files[i] = vtk
        end
    end
end

paraview_collection(mps_path) do pvd
    for i in 1:itr
        pvd[times[i]] = vtk_files[i]
    end
end
```
