### ISSUE TITLE
component_name kwarg consistency accross APIs

### ISSUE THREAD

**Issue by Antoinemarteau** [JuliaVTK/WriteVTK.jl#153]
While trying to properly export the field component names of vector / tensor fields in vtk format, I noticed possible inconsistencies:

- the kwarg `component_names` is documented in the docstring of `data_to_xml`, but not in that of `add_field_data`
- the possibility of passing kwargs is not documented in `setindex!(vtk::DatasetFile, ...)` (while it takes `component_names`)
- using the kwarg `component_names` is not possible in `sentindex!(pvtk::PVTKFile, ...)`

Are there particular reasons why the `component_names` kwarg are not available everywhere?
How hard would it be to make this kwarg available "everywhere" (I can try to do it) ?

**Comment by jipolanco** [comment]
I completely agree, thanks for noticing this inconsistency.

I just pushed #154 which should fix this issue. One should now be able to pass a `component_names` keyword argument to `setindex(pvtk::PVTKFile, ...)`. Let me know if that works for you.

**Comment by Antoinemarteau** [comment]
Thank you very much for the fast answer and implementation! 
I actually figured out that we don't export fields in pvtk ATM so I canno't test on my side, but this might be useful later or for others...
